### ISSUE TITLE
Crash when scrolling modules list

### ISSUE THREAD

**Issue by kapsh** [rovo89/XposedInstaller#288]
Hello. Xposed Installer crashes on my phone when I'm trying scroll down list of installed modules. 
And everytime  it happens if next visible item in list would be "Remember IME" (but I encountered with same crash with another module, deleting of them helped me both times). And I think this is not caused by one of my modules (I tried to disable them all and this didn't help). 

Which additional info you need? I have this log:

06-09 02:32:20.045 E/InputEventReceiver(16700): Exception dispatching input event. 
06-09 02:32:20.053 E/AndroidRuntime(16700): FATAL EXCEPTION: main 
06-09 02:32:20.053 E/AndroidRuntime(16700): Process: de.robv.android.xposed.installer, PID: 16700 
06-09 02:32:20.053 E/AndroidRuntime(16700): java.lang.NullPointerException 
06-09 02:32:20.053 E/AndroidRuntime(16700): at de.robv.android.xposed.installer.ModulesFragment$ModuleAdapter.getView(ModulesFragment.java:294) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.AbsListView.obtainView(AbsListView.java:2373) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.ListView.makeAndAddView(ListView.java:1812) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.ListView.fillDown(ListView.java:698) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.ListView.fillGap(ListView.java:662) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5772) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3478) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.AbsListView.onTouchMove(AbsListView.java:3949) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.widget.AbsListView.onTouchEvent(AbsListView.java:3728) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.View.dispatchTouchEvent(View.java:7880) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2316) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2013) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2120) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1552) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.app.Activity.dispatchTouchEvent(Activity.java:2499) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2068) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.View.dispatchPointerEvent(View.java:8071) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4392) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4263) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3935) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3992) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3859) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3828) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3836) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3809) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6124) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6104) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6058) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6254) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6216) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6276) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:816) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.Choreographer.doCallbacks(Choreographer.java:619) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.Choreographer.doFrame(Choreographer.java:586) 
06-09 02:32:20.053 E/AndroidRuntime(16700): at android.view.Choreographer$FrameDisplayEv

PS Can you tell me how to hide this log under spoiler? Thanks.

**Comment by rovo89** [comment]
Which version of the installer are you using?

**Comment by kapsh** [comment]
2.6.1 stable.
