### ISSUE TITLE
Installer 3.1.2 crash on downloading module update on nougat 

### ISSUE THREAD

**Issue by MarcinOrlowski** [rovo89/XposedInstaller#385]
Happens on OxygenOS 4.5.0 (7.1) on OnePlus3

```
java.lang.UnsupportedOperationException: Not a file URI: content://downloads/all_downloads/2393
	at de.robv.android.xposed.installer.util.DownloadsUtil.getFilenameFromUri(DownloadsUtil.java:472)
	at de.robv.android.xposed.installer.util.DownloadsUtil.getAllForUrl(DownloadsUtil.java:334)
	at de.robv.android.xposed.installer.util.DownloadsUtil.getLatestForUrl(DownloadsUtil.java:309)
	at de.robv.android.xposed.installer.widget.DownloadView.setUrl(DownloadView.java:160)
	at de.robv.android.xposed.installer.DownloadDetailsVersionsFragment$VersionsAdapter.getView(DownloadDetailsVersionsFragment.java:223)
	at android.widget.AbsListView.obtainView(AbsListView.java:2379)
	at android.widget.ListView.makeAndAddView(ListView.java:1970)
	at android.widget.ListView.fillDown(ListView.java:704)
	at android.widget.ListView.fillFromTop(ListView.java:765)
	at android.widget.ListView.layoutChildren(ListView.java:1744)
	at android.widget.AbsListView.onLayout(AbsListView.java:2171)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
	at android.view.View.layout(View.java:17745)
	at android.view.ViewGroup.layout(ViewGroup.java:5579)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2380)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2094)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1280)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6432)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:621)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
```

**Comment by daimoniuma** [comment]
Same on Lollipop.
```
java.lang.UnsupportedOperationException: Not a file URI: content://downloads/my_downloads/254
	at de.robv.android.xposed.installer.util.DownloadsUtil.getFilenameFromUri(DownloadsUtil.java:472)
	at de.robv.android.xposed.installer.util.DownloadsUtil.removeAllForLocalFile(DownloadsUtil.java:398)
	at de.robv.android.xposed.installer.util.DownloadsUtil.add(DownloadsUtil.java:154)
	at de.robv.android.xposed.installer.util.DownloadsUtil.access$000(DownloadsUtil.java:43)
	at de.robv.android.xposed.installer.util.DownloadsUtil$Builder.download(DownloadsUtil.java:102)
	at de.robv.android.xposed.installer.util.DownloadsUtil.addModule(DownloadsUtil.java:136)
	at de.robv.android.xposed.installer.widget.DownloadView$2.onClick(DownloadView.java:109)
	at android.view.View.performClick(View.java:4764)
	at android.view.View$PerformClick.run(View.java:19844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5356)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
```

**Comment by aaronpries** [comment]
I had the same issue (on OnePlus 3T, Android 7.1.1). It was fixed by uninstalling the XposedInstaller and doing a fresh installation.
