### ISSUE TITLE
Crashed while I was chenking the log.

### ISSUE THREAD

**Issue by nijigenirubasho** [rovo89/XposedInstaller#390]
FATAL EXCEPTION: main
Process: de.robv.android.xposed.installer, PID: 9224
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 524376 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
Caused by: android.os.TransactionTooLargeException: data parcel size 524376 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
	... 8 more

**Comment by rovo89** [comment]
I can't reproduce this, even with a ~5 MB logfile. Are you using the official installer.

**Comment by nijigenirubasho** [comment]
The model of my phone is Redmi Note 3 Pro.
I've cleared the cache & ART cache before.
When the crash came, I was trying to hook up a method that didn't exist.
So, the error logs multiplied instantly.
I swear I used the official application. Because I’ve already checked the signature.
My operation is to check the long log first by Xposed Installer, and then I click the recents navbar button. As do as #394.
I recorded all the logs while I am reproducing [this.](https://drive.google.com/open?id=0B9vRuBLxz4a0bjdRTGlLR1JEWDA)
I'm sorry I can only do so much.
