### ISSUE TITLE
Crash with long log

### ISSUE THREAD

**Issue by KaMyKaSii** [rovo89/XposedInstaller#394]
If you go to the Xposed Installer Logs tab while having a long log (which cuts off the start) and clicking the recents navbar button, the app will crash

` java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2051308 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3796)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
Caused by: android.os.TransactionTooLargeException: data parcel size 2051308 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3650)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3788)
	... 8 more`

**Comment by KaMyKaSii** [comment]
#390

**Comment by Baby1313** [comment]
#340
