### ISSUE TITLE
Attempt to invoke virtual method 'java.util.Set de.robv.android.xposed.installer.util.InstallZipUtil$XposedProp.getMissingInstallerFeatures()' on a null object reference

### ISSUE THREAD

**Issue by relan** [rovo89/XposedInstaller#398]
Compiled 6ee7753ee008b1225c257fa60bbe052e3df8f2c1 with no changes and clean-installed on a Android 7.1.2 device (Nexus 7 2013):

```
10-29 18:27:12.888   569   589 I ActivityManager: Displayed de.robv.android.xposed.installer/.WelcomeActivity: +742ms
10-29 18:27:12.985  1780  1780 D AndroidRuntime: Shutting down VM
10-29 18:27:12.986  1780  1780 E AndroidRuntime: FATAL EXCEPTION: main
10-29 18:27:12.986  1780  1780 E AndroidRuntime: Process: de.robv.android.xposed.installer, PID: 1780
10-29 18:27:12.986  1780  1780 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set de.robv.android.xposed.installer.util.InstallZipUtil$XposedProp.getMissingInstallerFeatures()' on a null object reference
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at de.robv.android.xposed.installer.installation.StatusInstallerFragment.refreshKnownIssue(StatusInstallerFragment.java:236)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at de.robv.android.xposed.installer.installation.StatusInstallerFragment.onCreateView(StatusInstallerFragment.java:114)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2353)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:816)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6121)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-29 18:27:12.986  1780  1780 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-29 18:27:12.988   569   897 W ActivityManager:   Force finishing activity de.robv.android.xposed.installer/.WelcomeActivity
10-29 18:27:13.063   569   434 I OpenGLRenderer: Initialized EGL, version 1.4
10-29 18:27:13.064   569   434 D OpenGLRenderer: Swap behavior 1
10-29 18:27:13.498   569   582 W ActivityManager: Activity pause timeout for ActivityRecord{6372fd1 u0 de.robv.android.xposed.installer/.WelcomeActivity t26 f}
10-29 18:27:14.125  1060  1170 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
10-29 18:27:14.760  1780  1809 I XposedInstaller: Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 1319328 bytes
10-29 18:27:14.766  1780  1809 W XposedRepoParser: skipping unknown/erronous tag: START_TAG <size>@39:13 in java.io.InputStreamReader@d98b266
10-29 18:27:14.767  1780  1809 W XposedRepoParser: skipping unknown/erronous tag: START_TAG <size>@66:13 in java.io.InputStreamReader@d98b266
10-29 18:27:14.768  1780  1809 W XposedRepoParser: skipping unknown/erronous tag: START_TAG <size>@91:13 in java.io.InputStreamReader@d98b266
10-29 18:27:14.769  1780  1809 W XposedRepoParser: skipping unknown/erronous tag: START_TAG <size>@123:13 in java.io.InputStreamReader@d98b266
```

Crashes right on start. This is a regression since 85551ec6632a06ee9e0eaf81b7b557ee54dd14cd. Xposed Framework 88.1 is installed.

**Comment by rovo89** [comment]
Thanks for reporting this, it's fixed now.
